sudo: false

language: node_js
node_js:
  - 6
  - 7

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S+)?$/

cache:
  directories:
    - demo/node_modules
    - node_modules
    - packages/uniforms/node_modules
    - packages/uniforms-antd/node_modules
    - packages/uniforms-bootstrap3/node_modules
    - packages/uniforms-bootstrap4/node_modules
    - packages/uniforms-material/node_modules
    - packages/uniforms-semantic/node_modules
    - packages/uniforms-unstyled/node_modules

before_script:
  - npm install --prefix demo

script:
  - npm test -- --runInBand

after_script:
  - npm run cover
  - npm run cover:report
